### ISSUE TITLE
Reduce characters on each console line

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/MissionScanner#6]
Currently, each line in the table contains about 128 characters. I think about 80 is normal for older console applications. It might be nice to reduce the character count per line, but it would require abbreviating, removing, or cutting off some data.

```C++
constexpr std::array<std::streamsize, 7> columnWidths{ 9, 48, 22, 24, 18, 2, 5 };
```

- Mission types could be abbreviated. Instead of Last one Standing, it could be LoS.
- Unit only column could be eliminated.
- Mission Description and map could be truncated if over X characters. 

It might be nice to just leave as is though so all data is displayed without truncating.

Column sizes are currently hardcoded. Making them variable sized based on missions being displayed would be a separate issue.

**Comment by DanRStevens** [comment]
I had some thoughts to add to this.

----

I like the idea of abbreviating game types to short codes. A legend could be printed ahead of the output. Similarly, the unit only missions could have a short one letter code, such as "U" to denote them, or nothing " " for a regular mission.

Possible Legend:
```
Cam = Campaign (Or E/Pxx for Eden/Plymouth and mission number)
Col = Colony (Or C if Campaign uses unambiguous alternate)
T = Tutorial
D = Demo
LoS = Last One Standing
LR = Land Rush
SR = Space Race
RR = Resource Race
M = Midas
```

```
U = Unit only mission
```

----

Aside from just abbreviating the type fields, we can also reduce column width for certain other fields. Notably the DLL name has a length restriction. Failing to abide by that causes weird in game behaviour, such as double listing of levels.

Map and tech tree names could be variable, though are typically of a certain length. We could potentially clip fields that are too long, or just have them overflow the column width and make the output a little ugly. One slightly ugly row here and there isn't too bad.

----

Maybe put the shorter fixed sized  columns on the left, and move the larger more variable sized columns to the right. By that token, the map description would come last.

Assuming players are searching for something, they may have certain requirements, such as the number of players supported, or the game type. This might make putting these fields first more helpful. Related would be the ability to sort output by a given column or set of columns.

Suggested column order:
```
Number of players
Mission type
Unit only mission
DLL name
Map name
Tech tree name
Map description
```

**Comment by Brett208** [comment]
What do you think about just putting the legend in the readme / console help?

**Comment by DanRStevens** [comment]
We could do that. I was thinking of just printing it ahead of the file table so it's always visible. Just maybe space it out a bit from the table so there is a visual break. Though I could see someone wanting to turn such output off, especially if they were going to postprocess the text output.

For the legend, maybe we should describe the DLL name encoding, rather than make up our own type designators. We could just remove the type column as the information is already visible in the DLL name.

**Comment by Brett208** [comment]
I'll tackle adding the legend. I'm a bit mixed on removing the type. I like being able to tell if the exported type name matches the filename. (You could probably check this via HxD I suppose).

Maybe a -L switch for adding the legend and list it default in the help?

**Comment by DanRStevens** [comment]
That's actually a really good point about detecting a type that's inconsistent with the DLL filename. I wonder if we should at some point add highlighting or reporting for inconsistencies like that. Same about `DescBlock` entries that don't contain pointers to the exported strings.

----

I've noticed quite a lot of programs will output a banner by default, but the banner can be silenced with some kind of `--quiet` option. That might be a good way to go. The legend is there by default, so people don't have to look for it, but it can be turned off if they need to process the output. Not sure if the column headings should be included in that, or if that should be a separate flag `--no-headings`.

----

Edit: Getting a bit unrelated, but we could also consider a long format that gives a lot more explicit detail about a level. It might be enabled by an option, or by specifying a specific filename, rather than a folder or wildcard. A long format might give one data field per line, and with longer form descriptions of the field, or cross reference information. If this is of interest, maybe we can open a new issue for it.

**Comment by Brett208** [comment]
I think it would be fine to expand MissionScanner both to have a long format and a banner that does basic checks. 

However, I was also going to post a release after finishing this issue and move on to other projects. (Not to say work cannot continue here).

I've got the legend working with the switch to turn off locally. I want to clean up a bit more before posting. It is complex in a couple of ways and hopefully acceptable.
